config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"


  namespace :admin do
    resources :partnerships, only: [:index]
    resources :dashboard, only: [:index]
    resources :contacts 
    resources :users, only: [:index, :show, :destroy]
  end

  resources :users do
    resources :dashboard, only: [:index]
    resources :partnerships, only: [:index, :show, :new, :create, :destroy]
    resources :contacts
    resources :designs do 
      resources :images, only: [:new, :create, :destroy, :show]
    end
  end

  # resources :contacts do
  #   resources :users
  # end
  # resources :partnerships
  # get '/admin' to: 'admin#index' #dahsboard

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

end

app/models/design.rb
class Design < ApplicationRecord
  validates   :name, :description, presence: true, uniqueness: true
  belongs_to  :user
  has_many    :images, dependent: :destroy
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  def index
    @designs = current_user.designs
  end

  def show
    @design = current_user.designs.find(params[:id])
    @images = @design.images.all
  end

  def new
    @design = Design.new
  end

  def create
    @design = current_user.designs.new(design_params)
    if @design.save
      flash[:success] = "Successfully created #{@design.name}!"
      redirect_to user_designs_path(current_user)
    else
      render :new
    end
  end

  def edit
    @design = Design.find(params[:id])
  end

  def update
    @design = Design.find(params[:id])
    @design.update(design_params)
    if @design.save
      flash[:success] = "#{@design.name} has been updated!"
      redirect_to user_design_path(current_user, @design)
    else
      render :edit
    end
  end

  def destroy
    @design = Design.find(params[:id])
    @design.destroy
    flash[:success] = "#{@design.name} has been deleted!"
    redirect_to user_designs_path(current_user)
  end

  private

  def design_params
    params.require(:design).permit(:name, :description)
  end

end

app/views/designs/_form.html.erb
<%= form_for [current_user, @design] do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    
    <br><br>

    <%= f.label :description %><br>
    <%= f.text_area :description %>

    <br><br>
    <div class = "images">
    <% if !@design.images.empty? %>
        <% @design.images.each do |image| %>
            <%= image_tag image.image.url, height: '200', width: 'auto' %><br>
            <%= link_to "Delete", user_design_image_path(current_user, @design, image), method: :delete%><br>
        <% end %>
    <% end %>
    </div>
    
    <br>
    
    <%= f.submit %>

<% end %>

app/views/designs/edit.html.erb
<div class = "wrapper">
<div class = "first-line">
<h1>Edit</h1>
<nav>
<%= link_to "Dashboard", user_dashboard_index_path(current_user) %>
<%= link_to "Portfolio", user_designs_path(current_user) %>
<%= link_to "Contacts", user_partnerships_path(current_user) %>
<%= link_to "Log Out", logout_path, method: :delete %></br>
</nav>
</div>
<div class = "content">

<%= render partial: 'form' %>
</div>
</div>

app/views/designs/index.html.erb
<div class = "wrapper">
  <div class = "first-line">
    <h1>All Designs:</h1>
    <nav>
      <%= link_to "Dashboard", user_dashboard_index_path(current_user) %>
      <%= link_to "Contacts", user_partnerships_path(current_user) %>
      <%= link_to "Log Out", logout_path, method: :delete %></br>
    </nav>
  </div>
  <div class = "content">

  <ul>
  <% @designs.reverse.each do |design| %>
    <li>
    <%= link_to "#{design.name}", user_design_path(current_user, design) %><br>
    Posted <%= distance_of_time_in_words(Time.now, design.created_at) %> ago
    <%= link_to "Edit", edit_user_design_path(current_user, design) %>
    <%= link_to "Delete", user_design_path(current_user, design), method: :delete %>
    
    
      <% if design.images.exists? %>
    <br><br>
    <% design.images.each do |image| %>
      <%= image_tag image.image.url, width: '100', height: 'auto' %>
    <% end %>
    <br><br>
  <% end %>

    
    </li>
  <% end %>
  </ul>

  <div class = "new-des">
    <%= link_to "New Design", new_user_design_path(current_user) %>
  </div>
</div>

</div>

app/views/designs/new.html.erb
<div class = "wrapper">
<div class = "first-line">
<h1>New Design</h1>
<nav>
<%= link_to "Dashboard", user_dashboard_index_path(current_user) %>
<%= link_to "Portfolio", user_designs_path(current_user) %>
<%= link_to "Contacts", user_partnerships_path(current_user) %>
<%= link_to "Log Out", logout_path, method: :delete %></br>
</nav>
</div>

<div class = "content">

<%= render partial: 'form' %>
</div>
</div>

app/views/designs/show.html.erb
<div class = "wrapper">
<div class = "first-line">
<h1><%= @design.name %></h1>
<nav>
<%= link_to "Dashboard", user_dashboard_index_path(current_user) %>
<%= link_to "Portfolio", user_designs_path(current_user) %>
<%= link_to "Contacts", user_partnerships_path(current_user) %>
<%= link_to "Log Out", logout_path, method: :delete %></br>
</nav>
</div>
<div class = "content">

Design No. <strong><%= @design.id %><br><br></strong>
Description: <strong><%= @design.description %><br><br></strong>

<div class = "design image">
    <% @images.each do |image| %>
        <%= link_to image_tag(image.image.url, width: '300', height: 'auto'), user_design_image_path(current_user, @design, image) %>
    <% end %>
</div><br>

<%= link_to "Upload Image", new_user_design_image_path(current_user,@design) %>
<br>
</br><%= link_to "Edit", edit_user_design_path(current_user, @design) %>
</br><%= link_to "Delete", user_design_path(current_user, @design), method: :delete %>
</div>
</div>