config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"


  namespace :admin do
    resources :partnerships, only: [:index]
    resources :dashboard, only: [:index]
    resources :contacts 
    resources :users, only: [:index, :show, :destroy]
  end

  resources :users do
    resources :dashboard, only: [:index]
    resources :partnerships, only: [:index, :show, :new, :create, :destroy]
    resources :contacts
    resources :designs do 
      resources :images, only: [:new, :create, :destroy, :show]
    end
  end

  # resources :contacts do
  #   resources :users
  # end
  # resources :partnerships
  # get '/admin' to: 'admin#index' #dahsboard

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

end

app/models/partnership.rb
class Partnership < ApplicationRecord
    belongs_to :contact
    belongs_to :user    
    validates_uniqueness_of :user_id, {scope: :contact_id}
end

app/controllers/admin/partnerships_controller.rb
class Admin::PartnershipsController < Admin::BaseController
    
    def index
        @partnerships = Partnership.all
    end

end

app/controllers/partnerships_controller.rb
class PartnershipsController < ApplicationController


  def index
    @partnerships = current_user.partnerships
    @partnership = Partnership.new
  end

  def new
  end

  def create
    @user = User.find(current_user.id)
    @partnership = @user.partnerships.create(user: current_user, contact_id: partnership_params[:contact_id])
    redirect_to user_partnerships_path(@user)
  end

  def destroy
    @partnership = current_user.partnerships.find(params[:id])
    @partnership.destroy
    redirect_to user_partnerships_path(current_user)
  end

  private

  def partnership_params
    params.require(:partnership).permit(:user_id, :contact_id)
  end
  
end

app/views/admin/partnerships/index.html.erb
<div class = "wrapper">
<div class = "first-line">

<h1>Partnerships</h1>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Designers", admin_users_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">

<ul>
<% @partnerships.each do |partnership| %>
    <li>
    <%= link_to "#{partnership.user.company_name}", admin_user_path(partnership.user) %> and <%= link_to "#{partnership.contact.company}", admin_contact_path(partnership.contact) %>    
    </li>
<% end %>
</ul>
</div>
</div>