config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"


  namespace :admin do
    resources :partnerships, only: [:index]
    resources :dashboard, only: [:index]
    resources :contacts 
    resources :users, only: [:index, :show, :destroy]
  end

  resources :users do
    resources :dashboard, only: [:index]
    resources :partnerships, only: [:index, :show, :new, :create, :destroy]
    resources :contacts
    resources :designs do 
      resources :images, only: [:new, :create, :destroy, :show]
    end
  end

  # resources :contacts do
  #   resources :users
  # end
  # resources :partnerships
  # get '/admin' to: 'admin#index' #dahsboard

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :company, :contact_name, :location, :phone_number, :email, :industry, presence: true
    validates_uniqueness_of :company, :contact_name
    has_many :partnerships, dependent: :destroy
    has_many :users, through: :partnerships
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::BaseController

    def index
        @contacts = Contact.all
    end
    
    def new
        @admin = current_user
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            flash[:success] = "You created #{@contact.contact_name} at #{@contact.company}!"
            redirect_to admin_contacts_path
        else
            flash[:alert] = "#{@contact.contact_name} at #{@contact.company} already exists!"            
            render :new
        end
    end

    def show
        @contact = Contact.find(params[:id])
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def update
        @contact = Contact.find(params[:id])
        @contact.update(contact_params)
        if @contact.save
            flash[:success] = "#{@contact.contact_name} updated!"
            redirect_to admin_contact_path(@contact)
        else
            redirect_to admin_contacts_path
        end
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
        flash[:success] = "#{@contact.contact_name} has been deleted!"
        redirect_to admin_contacts_path
    end

    private

    def contact_params
        params.require(:contact).permit(:company, :contact_name, :location, :phone_number, :email, :industry)        
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
            @user = current_user
            @user_contacts = @user.contacts
            @partnerships = @user.partnerships
    end

    def show
        @contact = Contact.find(params[:id])
    end

    def create
        @partnership = Partnership.create(partnership_params)
    end

    private

    def contact_params
        params.require(:contact).permit(:company, :contact_name, :location, :phone_number, :email, :industry)
    end

    def partnership_params
        params.require(:partnership).permit(current_user, :contact)
    end


end

app/views/admin/contacts/edit.html.erb
<div class = "wrapper">
<div class = "first-line">
<h1>Edit</h1>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Partnerships", admin_partnerships_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Designers", admin_users_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">
<%= form_for(([current_user, @contact]), url: admin_contact_path(@contact)) do |f| %>
    <%= f.label :contact_name %>
    <%= f.text_field :contact_name %></br></br>

    <%= f.label :company %>
    <%= f.text_field :company %></br></br>

    <%= f.label :location %>
    <%= f.text_field :location %></br></br>

    <%= f.label :email %>
    <%= f.text_field :email %></br></br>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %></br></br>

    <%= f.label :industry %>
    <%= f.select :industry, ["Manufacturer", "Retailer", "Buyer"] %></br></br>

    <%= f.submit %></br>

<% end %>    
</div>

</div>

app/views/admin/contacts/index.html.erb
<div class = "wrapper">
    <div class = "first-line">
        <h1>Contacts</h1>
        <nav>
        <%= link_to "Dashboard", admin_dashboard_index_path %>
        <%= link_to "Partnerships", admin_partnerships_path %>
        <%= link_to "Designers", admin_users_path %>
        <%= link_to "Log Out", logout_path, method: :delete %>
        </nav>
    </div>

<div class = "content" id = "contact-index">
<ul>
<% @contacts.each do |contact| %>
<li>
<%= link_to "#{contact.contact_name} @ #{contact.company}", admin_contact_path(contact) %>
<%= link_to "Edit", edit_admin_contact_path(contact) %>
<%= link_to "Delete", admin_contact_path(contact), method: "delete" %>
</li>
<% end %>

</ul>
<div class = "new-contact">
<%= link_to "New Contact", new_admin_contact_path %>
</div>
</div>
</div>

app/views/admin/contacts/new.html.erb
<div class = "wrapper">
<div class = "first-line">

<h1>New Contact</h1>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Partnerships", admin_partnerships_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Designers", admin_users_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">

<%= form_for(([@admin, @contact]), url: admin_contacts_path) do |f|%>
    <%= f.label :company %>
    <%= f.text_field :company %> <br/><br/>

    <%= f.label :contact_name %>
    <%= f.text_field :contact_name %><br/><br/>

    <%= f.label :location %>
    <%= f.text_field :location %><br/><br/>

    <%= f.label :email %>
    <%= f.text_field :email %><br/><br/>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %><br/><br/>

    <%= f.label :industry %>
    <%= f.select :industry, ["Manufacturer", "Retailer", "Buyer"] %><br/><br/>

    <%= f.submit %>
<% end %>
</div>
</div>

app/views/admin/contacts/show.html.erb
<div class = "wrapper">
<div class = "first-line">



<h1><%= @contact.company %></h1></br>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Partnerships", admin_partnerships_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Designers", admin_users_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">

Contact Name: <%= @contact.contact_name %></br>

Location: <%= @contact.location %></br>

Phone Number: <%= @contact.phone_number %></br>

E-mail: <%= @contact.email %></br>

Industry: <%= @contact.industry %></br>

<%= link_to "Edit", edit_admin_contact_path %>
<%= link_to "Delete", admin_contact_path(@contact), method: "delete" %>

</div>
</div>