config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"


  namespace :admin do
    resources :partnerships, only: [:index]
    resources :dashboard, only: [:index]
    resources :contacts 
    resources :users, only: [:index, :show, :destroy]
  end

  resources :users do
    resources :dashboard, only: [:index]
    resources :partnerships, only: [:index, :show, :new, :create, :destroy]
    resources :contacts
    resources :designs do 
      resources :images, only: [:new, :create, :destroy, :show]
    end
  end

  # resources :contacts do
  #   resources :users
  # end
  # resources :partnerships
  # get '/admin' to: 'admin#index' #dahsboard

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :location, :company_name, :website, presence: true
  validates_uniqueness_of :email, :company_name, :website
  has_many :designs
  has_many :partnerships
  has_many :contacts, through: :partnerships
  enum role: ["default", "admin"]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

    def index
        @users = User.where(role: "default")
    end

    def show
        @user = User.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_dashboard_index_path(@user)
    else
      render :new
      # flash[:notice] = "One or more of your login credentials have already been used!"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:company_name,:website,:location,:role)
  end

end

app/views/admin/users/index.html.erb
<div class = "wrapper">
<div class = "first-line">


<h1>Designers</h1>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Partnerships", admin_partnerships_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">

<ul>
<% @users.each do |user| %>
    <li>
    <%= link_to "#{user.email} @ #{user.company_name}", admin_user_path(user) %>    
    </li>
<% end %>
</ul>
</div>
</div>

app/views/admin/users/show.html.erb
<div class = "wrapper">
<div class = "first-line">

<h1><%= @user.company_name %></h1></br>
<nav>
<%= link_to "Dashboard", admin_dashboard_index_path %>
<%= link_to "Partnerships", admin_partnerships_path %>
<%= link_to "Contacts", admin_contacts_path %>
<%= link_to "Designers", admin_users_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
</nav>
</div>
<div class = "content">

Email: <%= @user.email %></br>

Location: <%= @user.location %></br>

Website: <%= @user.website %></br>

</div>
</div>